//
// Register Declarations for Microchip 16F685 Processor
//
//
// This header file was automatically generated by:
//
//	inc2h.pl V1.5
//
//	Copyright (c) 2002, Kevin L. Pauba, All Rights Reserved
//
//	SDCC is licensed under the GNU Public license (GPL) v2.  Note that
//	this license covers the code to the compiler and other executables,
//	but explicitly does not cover any code or objects generated by sdcc.
//	We have not yet decided on a license for the run time libraries, but
//	it will not put any requirements on code linked against it. See:
// 
//	http://www.gnu.org/copyleft/gpl/html
//
//	See http://sdcc.sourceforge.net/ for the latest information on sdcc.
//
// 
#ifndef P16F685_H
#define P16F685_H

#ifndef BIT_AT
#define BIT_AT(base,bitno) sbit at ((base<<3)+bitno)
#endif

//
// Register addresses.
//
#define INDF_ADDR	0x0000
#define TMR0_ADDR	0x0001
#define PCL_ADDR	0x0002
#define STATUS_ADDR	0x0003
#define FSR_ADDR	0x0004
#define PORTA_ADDR	0x0005
#define PORTB_ADDR	0x0006
#define PORTC_ADDR	0x0007
#define PCLATH_ADDR	0x000A
#define INTCON_ADDR	0x000B
#define PIR1_ADDR	0x000C
#define PIR2_ADDR	0x000D
#define TMR1L_ADDR	0x000E
#define TMR1H_ADDR	0x000F
#define T1CON_ADDR	0x0010
#define TMR2_ADDR	0x0011
#define T2CON_ADDR	0x0012
#define CCPR1L_ADDR	0x0015
#define CCPR1H_ADDR	0x0016
#define CCP1CON_ADDR	0x0017
#define PWM1CON_ADDR	0x001C
#define ECCPAS_ADDR	0x001D
#define ADRESH_ADDR	0x001E
#define ADCON0_ADDR	0x001F
#define OPTION_REG_ADDR	0x0081
#define TRISA_ADDR	0x0085
#define TRISB_ADDR	0x0086
#define TRISC_ADDR	0x0087
#define PIE1_ADDR	0x008C
#define PIE2_ADDR	0x008D
#define PCON_ADDR	0x008E
#define OSCCON_ADDR	0x008F
#define OSCTUNE_ADDR	0x0090
#define PR2_ADDR	0x0092
#define WPU_ADDR	0x0095
#define WPUA_ADDR	0x0095
#define IOC_ADDR	0x0096
#define IOCA_ADDR	0x0096
#define WDTCON_ADDR	0x0097
#define ADRESL_ADDR	0x009E
#define ADCON1_ADDR	0x009F
#define EEDATA_ADDR	0x010C
#define EEADR_ADDR	0x010D
#define EEDATH_ADDR	0x010E
#define EEADRH_ADDR	0x010F
#define WPUB_ADDR	0x0115
#define IOCB_ADDR	0x0116
#define VRCON_ADDR	0x0118
#define CM1CON0_ADDR	0x0119
#define CM2CON0_ADDR	0x011A
#define CM2CON1_ADDR	0x011B
#define ANSEL_ADDR	0x011E
#define ANSELH_ADDR	0x011F
#define EECON1_ADDR	0x018C
#define EECON2_ADDR	0x018D
#define PSTRCON_ADDR	0x019D
#define SRCON_ADDR	0x019E

//
// Memory organization.
//
#pragma maxram 0x1FF


#pragma memmap INDF_ADDR INDF_ADDR SFR 0x000	// INDF
#pragma memmap TMR0_ADDR TMR0_ADDR SFR 0x000	// TMR0
#pragma memmap PCL_ADDR PCL_ADDR SFR 0x000	// PCL
#pragma memmap STATUS_ADDR STATUS_ADDR SFR 0x000	// STATUS
#pragma memmap FSR_ADDR FSR_ADDR SFR 0x000	// FSR
#pragma memmap PORTA_ADDR PORTA_ADDR SFR 0x000	// PORTA
#pragma memmap PORTB_ADDR PORTB_ADDR SFR 0x000	// PORTB
#pragma memmap PORTC_ADDR PORTC_ADDR SFR 0x000	// PORTC
#pragma memmap PCLATH_ADDR PCLATH_ADDR SFR 0x000	// PCLATH
#pragma memmap INTCON_ADDR INTCON_ADDR SFR 0x000	// INTCON
#pragma memmap PIR1_ADDR PIR1_ADDR SFR 0x000	// PIR1
#pragma memmap PIR2_ADDR PIR2_ADDR SFR 0x000	// PIR2
#pragma memmap TMR1L_ADDR TMR1L_ADDR SFR 0x000	// TMR1L
#pragma memmap TMR1H_ADDR TMR1H_ADDR SFR 0x000	// TMR1H
#pragma memmap T1CON_ADDR T1CON_ADDR SFR 0x000	// T1CON
#pragma memmap TMR2_ADDR TMR2_ADDR SFR 0x000	// TMR2
#pragma memmap T2CON_ADDR T2CON_ADDR SFR 0x000	// T2CON
#pragma memmap CCPR1L_ADDR CCPR1L_ADDR SFR 0x000	// CCPR1L
#pragma memmap CCPR1H_ADDR CCPR1H_ADDR SFR 0x000	// CCPR1H
#pragma memmap CCP1CON_ADDR CCP1CON_ADDR SFR 0x000	// CCP1CON
#pragma memmap PWM1CON_ADDR PWM1CON_ADDR SFR 0x000	// PWM1CON
#pragma memmap ECCPAS_ADDR ECCPAS_ADDR SFR 0x000	// ECCPAS
#pragma memmap ADRESH_ADDR ADRESH_ADDR SFR 0x000	// ADRESH
#pragma memmap ADCON0_ADDR ADCON0_ADDR SFR 0x000	// ADCON0
#pragma memmap OPTION_REG_ADDR OPTION_REG_ADDR SFR 0x000	// OPTION_REG
#pragma memmap TRISA_ADDR TRISA_ADDR SFR 0x000	// TRISA
#pragma memmap TRISB_ADDR TRISB_ADDR SFR 0x000	// TRISB
#pragma memmap TRISC_ADDR TRISC_ADDR SFR 0x000	// TRISC
#pragma memmap PIE1_ADDR PIE1_ADDR SFR 0x000	// PIE1
#pragma memmap PIE2_ADDR PIE2_ADDR SFR 0x000	// PIE2
#pragma memmap PCON_ADDR PCON_ADDR SFR 0x000	// PCON
#pragma memmap OSCCON_ADDR OSCCON_ADDR SFR 0x000	// OSCCON
#pragma memmap OSCTUNE_ADDR OSCTUNE_ADDR SFR 0x000	// OSCTUNE
#pragma memmap PR2_ADDR PR2_ADDR SFR 0x000	// PR2
#pragma memmap WPU_ADDR WPU_ADDR SFR 0x000	// WPU
#pragma memmap WPUA_ADDR WPUA_ADDR SFR 0x000	// WPUA
#pragma memmap IOC_ADDR IOC_ADDR SFR 0x000	// IOC
#pragma memmap IOCA_ADDR IOCA_ADDR SFR 0x000	// IOCA
#pragma memmap WDTCON_ADDR WDTCON_ADDR SFR 0x000	// WDTCON
#pragma memmap ADRESL_ADDR ADRESL_ADDR SFR 0x000	// ADRESL
#pragma memmap ADCON1_ADDR ADCON1_ADDR SFR 0x000	// ADCON1
#pragma memmap EEDATA_ADDR EEDATA_ADDR SFR 0x000	// EEDATA
#pragma memmap EEADR_ADDR EEADR_ADDR SFR 0x000	// EEADR
#pragma memmap EEDATH_ADDR EEDATH_ADDR SFR 0x000	// EEDATH
#pragma memmap EEADRH_ADDR EEADRH_ADDR SFR 0x000	// EEADRH
#pragma memmap WPUB_ADDR WPUB_ADDR SFR 0x000	// WPUB
#pragma memmap IOCB_ADDR IOCB_ADDR SFR 0x000	// IOCB
#pragma memmap VRCON_ADDR VRCON_ADDR SFR 0x000	// VRCON
#pragma memmap CM1CON0_ADDR CM1CON0_ADDR SFR 0x000	// CM1CON0
#pragma memmap CM2CON0_ADDR CM2CON0_ADDR SFR 0x000	// CM2CON0
#pragma memmap CM2CON1_ADDR CM2CON1_ADDR SFR 0x000	// CM2CON1
#pragma memmap ANSEL_ADDR ANSEL_ADDR SFR 0x000	// ANSEL
#pragma memmap ANSELH_ADDR ANSELH_ADDR SFR 0x000	// ANSELH
#pragma memmap EECON1_ADDR EECON1_ADDR SFR 0x000	// EECON1
#pragma memmap EECON2_ADDR EECON2_ADDR SFR 0x000	// EECON2
#pragma memmap PSTRCON_ADDR PSTRCON_ADDR SFR 0x000	// PSTRCON
#pragma memmap SRCON_ADDR SRCON_ADDR SFR 0x000	// SRCON


//         LIST
// P16F685.INC  Standard Header File, Version 1.00    Microchip Technology, Inc.
//         NOLIST

// This header file defines configurations, registers, and other useful bits of
// information for the PIC16F685 microcontroller.  These names are taken to match 
// the data sheets as closely as possible.  

// Note that the processor must be selected before this file is 
// included.  The processor may be selected the following ways:

//       1. Command line switch:
//               C:\ MPASM MYFILE.ASM /PIC16F685
//       2. LIST directive in the source file
//               LIST   P=PIC16F685
//       3. Processor Type entry in the MPASM full-screen interface

//==========================================================================
//
//       Revision History
//
//==========================================================================
//1.00   10/12/04 Original
//==========================================================================
//
//       Verify Processor
//
//==========================================================================

//        IFNDEF __16F685
//            MESSG "Processor-header file mismatch.  Verify selected processor."
//         ENDIF

//==========================================================================
//
//       Register Definitions
//
//==========================================================================

#define W                    0x0000
#define F                    0x0001

//----- Register Files------------------------------------------------------

data at INDF_ADDR volatile char        INDF;
sfr  at TMR0_ADDR                      TMR0;
data at PCL_ADDR volatile char         PCL;
sfr  at STATUS_ADDR                    STATUS;
sfr  at FSR_ADDR                       FSR;
sfr  at PORTA_ADDR                     PORTA;
sfr  at PORTB_ADDR                     PORTB;
sfr  at PORTC_ADDR                     PORTC;

sfr  at PCLATH_ADDR                    PCLATH;
sfr  at INTCON_ADDR                    INTCON;
sfr  at PIR1_ADDR                      PIR1;
sfr  at PIR2_ADDR                      PIR2;
sfr  at TMR1L_ADDR                     TMR1L;		
sfr  at TMR1H_ADDR                     TMR1H;		
sfr  at T1CON_ADDR                     T1CON;		
sfr  at TMR2_ADDR                      TMR2;
sfr  at T2CON_ADDR                     T2CON;


sfr  at CCPR1L_ADDR                    CCPR1L;
sfr  at CCPR1H_ADDR                    CCPR1H;
sfr  at CCP1CON_ADDR                   CCP1CON;


sfr  at PWM1CON_ADDR                   PWM1CON;
sfr  at ECCPAS_ADDR                    ECCPAS;
sfr  at ADRESH_ADDR                    ADRESH;		
sfr  at ADCON0_ADDR                    ADCON0;		


sfr  at OPTION_REG_ADDR                OPTION_REG;

sfr  at TRISA_ADDR                     TRISA;
sfr  at TRISB_ADDR                     TRISB;
sfr  at TRISC_ADDR                     TRISC;

sfr  at PIE1_ADDR                      PIE1;
sfr  at PIE2_ADDR                      PIE2;
sfr  at PCON_ADDR                      PCON;
sfr  at OSCCON_ADDR                    OSCCON;
sfr  at OSCTUNE_ADDR                   OSCTUNE;

sfr  at PR2_ADDR                       PR2;


sfr  at WPU_ADDR                       WPU;
sfr  at WPUA_ADDR                      WPUA;
sfr  at IOC_ADDR                       IOC;
sfr  at IOCA_ADDR                      IOCA;
sfr  at WDTCON_ADDR                    WDTCON;



sfr  at ADRESL_ADDR                    ADRESL;		
sfr  at ADCON1_ADDR                    ADCON1;



sfr  at EEDATA_ADDR                    EEDATA;
sfr  at EEADR_ADDR                     EEADR;
sfr  at EEDATH_ADDR                    EEDATH;
sfr  at EEADRH_ADDR                    EEADRH;


sfr  at WPUB_ADDR                      WPUB;
sfr  at IOCB_ADDR                      IOCB;

sfr  at VRCON_ADDR                     VRCON;
sfr  at CM1CON0_ADDR                   CM1CON0;
sfr  at CM2CON0_ADDR                   CM2CON0;
sfr  at CM2CON1_ADDR                   CM2CON1;

sfr  at ANSEL_ADDR                     ANSEL;
sfr  at ANSELH_ADDR                    ANSELH;

sfr  at EECON1_ADDR                    EECON1;
sfr  at EECON2_ADDR                    EECON2;


sfr  at PSTRCON_ADDR                   PSTRCON;
sfr  at SRCON_ADDR                     SRCON;



//----- BANK 0 REGISTER DEFINITIONS ----------------------------------------
//----- STATUS Bits --------------------------------------------------------

BIT_AT(STATUS_ADDR,7)	IRP;
BIT_AT(STATUS_ADDR,6)	RP1;
BIT_AT(STATUS_ADDR,5)	RP0;
BIT_AT(STATUS_ADDR,4)	NOT_TO;
BIT_AT(STATUS_ADDR,3)	NOT_PD;
BIT_AT(STATUS_ADDR,2)	Z;
BIT_AT(STATUS_ADDR,1)	DC;
BIT_AT(STATUS_ADDR,0)	C;

//----- INTCON Bits --------------------------------------------------------

BIT_AT(INTCON_ADDR,7)	GIE;
BIT_AT(INTCON_ADDR,6)	PEIE;
BIT_AT(INTCON_ADDR,5)	T0IE;
BIT_AT(INTCON_ADDR,4)	INTE;
BIT_AT(INTCON_ADDR,3)	RABIE;
BIT_AT(INTCON_ADDR,2)	T0IF;
BIT_AT(INTCON_ADDR,1)	INTF;
BIT_AT(INTCON_ADDR,0)	RABIF;

//----- PIR1 Bits ----------------------------------------------------------

BIT_AT(PIR1_ADDR,6)	ADIF;


BIT_AT(PIR1_ADDR,2)	CCP1IF;
BIT_AT(PIR1_ADDR,1)	T2IF;
BIT_AT(PIR1_ADDR,1)	TMR2IF;
BIT_AT(PIR1_ADDR,0)	T1IF;
BIT_AT(PIR1_ADDR,0)	TMR1IF;

//----- PIR2 Bits ----------------------------------------------------------

BIT_AT(PIR2_ADDR,7)	OSFIF;
BIT_AT(PIR2_ADDR,6)	C2IF;
BIT_AT(PIR2_ADDR,5)	C1IF;
BIT_AT(PIR2_ADDR,4)	EEIF;

//----- T1CON Bits ---------------------------------------------------------

BIT_AT(T1CON_ADDR,7)	T1GINV;
BIT_AT(T1CON_ADDR,6)	TMR1GE;
BIT_AT(T1CON_ADDR,5)	T1CKPS1;
BIT_AT(T1CON_ADDR,4)	T1CKPS0;
BIT_AT(T1CON_ADDR,3)	T1OSCEN;
BIT_AT(T1CON_ADDR,2)	NOT_T1SYNC;
BIT_AT(T1CON_ADDR,1)	TMR1CS;
BIT_AT(T1CON_ADDR,0)	TMR1ON;

//----- T2CON Bits ---------------------------------------------------------

BIT_AT(T2CON_ADDR,6)	TOUTPS3;
BIT_AT(T2CON_ADDR,5)	TOUTPS2;
BIT_AT(T2CON_ADDR,4)	TOUTPS1;
BIT_AT(T2CON_ADDR,3)	TOUTPS0;
BIT_AT(T2CON_ADDR,2)	TMR2ON;
BIT_AT(T2CON_ADDR,1)	T2CKPS1;
BIT_AT(T2CON_ADDR,0)	T2CKPS0;


//----- CCP1CON Bits -------------------------------------------------------

BIT_AT(CCP1CON_ADDR,7)	P1M1;
BIT_AT(CCP1CON_ADDR,6)	P1M0;
BIT_AT(CCP1CON_ADDR,5)	DC1B1;
BIT_AT(CCP1CON_ADDR,4)	DC1B0;
BIT_AT(CCP1CON_ADDR,3)	CCP1M3;
BIT_AT(CCP1CON_ADDR,2)	CCP1M2;
BIT_AT(CCP1CON_ADDR,1)	CCP1M1;
BIT_AT(CCP1CON_ADDR,0)	CCP1M0;

//----- PWM1CON Bits -------------------------------------------------------

BIT_AT(PWM1CON_ADDR,7)	PRSEN;
BIT_AT(PWM1CON_ADDR,6)	PDC6;
BIT_AT(PWM1CON_ADDR,5)	PDC5;
BIT_AT(PWM1CON_ADDR,4)	PDC4;
BIT_AT(PWM1CON_ADDR,3)	PDC3;
BIT_AT(PWM1CON_ADDR,2)	PDC2;
BIT_AT(PWM1CON_ADDR,1)	PDC1;
BIT_AT(PWM1CON_ADDR,0)	PDC0;

//----- ECCPAS Bits --------------------------------------------------------

BIT_AT(ECCPAS_ADDR,7)	ECCPASE;
BIT_AT(ECCPAS_ADDR,6)	ECCPAS2;
BIT_AT(ECCPAS_ADDR,5)	ECCPAS1;
BIT_AT(ECCPAS_ADDR,4)	ECCPAS0;
BIT_AT(ECCPAS_ADDR,3)	PSSAC1;
BIT_AT(ECCPAS_ADDR,2)	PSSAC0;
BIT_AT(ECCPAS_ADDR,1)	PSSBD1;
BIT_AT(ECCPAS_ADDR,0)	PSSBD0;

//----- ADCON0 Bits --------------------------------------------------------

BIT_AT(ADCON0_ADDR,7)	ADFM;
BIT_AT(ADCON0_ADDR,6)	VCFG;
BIT_AT(ADCON0_ADDR,5)	CHS3;
BIT_AT(ADCON0_ADDR,4)	CHS2;
BIT_AT(ADCON0_ADDR,3)	CHS1;
BIT_AT(ADCON0_ADDR,2)	CHS0;
BIT_AT(ADCON0_ADDR,1)	GO;
BIT_AT(ADCON0_ADDR,1)	NOT_DONE;
BIT_AT(ADCON0_ADDR,1)	GO_DONE;
BIT_AT(ADCON0_ADDR,0)	ADON;

//----- BANK 1 REGISTER DEFINITIONS ----------------------------------------
//----- OPTION Bits --------------------------------------------------------

BIT_AT(OPTION_REG_ADDR,7)	NOT_RABPU;
BIT_AT(OPTION_REG_ADDR,6)	INTEDG;
BIT_AT(OPTION_REG_ADDR,5)	T0CS;
BIT_AT(OPTION_REG_ADDR,4)	T0SE;
BIT_AT(OPTION_REG_ADDR,3)	PSA;
BIT_AT(OPTION_REG_ADDR,2)	PS2;
BIT_AT(OPTION_REG_ADDR,1)	PS1;
BIT_AT(OPTION_REG_ADDR,0)	PS0;

//----- TRISA Bits --------------------------------------------------------

BIT_AT(TRISA_ADDR,5)	TRISA5;
BIT_AT(TRISA_ADDR,4)	TRISA4;
BIT_AT(TRISA_ADDR,3)	TRISA3;
BIT_AT(TRISA_ADDR,2)	TRISA2;
BIT_AT(TRISA_ADDR,1)	TRISA1;
BIT_AT(TRISA_ADDR,0)	TRISA0;

//----- TRISB Bits --------------------------------------------------------

BIT_AT(TRISB_ADDR,7)	TRISB7;
BIT_AT(TRISB_ADDR,6)	TRISB6;
BIT_AT(TRISB_ADDR,5)	TRISB5;
BIT_AT(TRISB_ADDR,4)	TRISB4;

//----- TRISC Bits --------------------------------------------------------

BIT_AT(TRISC_ADDR,7)	TRISC7;
BIT_AT(TRISC_ADDR,6)	TRISC6;
BIT_AT(TRISC_ADDR,5)	TRISC5;
BIT_AT(TRISC_ADDR,4)	TRISC4;
BIT_AT(TRISC_ADDR,3)	TRISC3;
BIT_AT(TRISC_ADDR,2)	TRISC2;
BIT_AT(TRISC_ADDR,1)	TRISC1;
BIT_AT(TRISC_ADDR,0)	TRISC0;

//----- PIE1 Bits ----------------------------------------------------------

BIT_AT(PIE1_ADDR,6)	ADIE;


BIT_AT(PIE1_ADDR,2)	CCPIE;
BIT_AT(PIE1_ADDR,1)	T2IE;
BIT_AT(PIE1_ADDR,1)	TMR2IE;
BIT_AT(PIE1_ADDR,0)	T1IE;
BIT_AT(PIE1_ADDR,0)	TMR1IE;

//----- PIE2 Bits ----------------------------------------------------------

BIT_AT(PIE2_ADDR,7)	OSFIE;
BIT_AT(PIE2_ADDR,6)	C2IE;
BIT_AT(PIE2_ADDR,5)	C1IE;
BIT_AT(PIE2_ADDR,4)	EEIE;

//----- PCON Bits ----------------------------------------------------------

BIT_AT(PCON_ADDR,5)	ULPWUE;
BIT_AT(PCON_ADDR,4)	SBODEN;
BIT_AT(PCON_ADDR,1)	NOT_POR;
BIT_AT(PCON_ADDR,0)	NOT_BOD;

//----- OSCCON Bits --------------------------------------------------------

BIT_AT(OSCCON_ADDR,6)	IRCF2;
BIT_AT(OSCCON_ADDR,5)	IRCF1;
BIT_AT(OSCCON_ADDR,4)	IRCF0;
BIT_AT(OSCCON_ADDR,3)	OSTS;
BIT_AT(OSCCON_ADDR,2)	HTS;
BIT_AT(OSCCON_ADDR,1)	LTS;
BIT_AT(OSCCON_ADDR,0)	SCS;

//----- OSCTUNE Bits -------------------------------------------------------

BIT_AT(OSCTUNE_ADDR,4)	TUN4;
BIT_AT(OSCTUNE_ADDR,3)	TUN3;
BIT_AT(OSCTUNE_ADDR,2)	TUN2;
BIT_AT(OSCTUNE_ADDR,1)	TUN1;
BIT_AT(OSCTUNE_ADDR,0)	TUN0;

//----- WPUA --------------------------------------------------------------

#define WPUA5                0x0005
#define WPUA4                0x0004

#define WPUA2                0x0002
#define WPUA1                0x0001
#define WPUA0                0x0000

//----- IOC --------------------------------------------------------------

#define IOC5                 0x0005
#define IOC4                 0x0004
#define IOC3                 0x0003
#define IOC2                 0x0002
#define IOC1                 0x0001
#define IOC0                 0x0000

//----- IOCA --------------------------------------------------------------

#define IOCA5                0x0005
#define IOCA4                0x0004
#define IOCA3                0x0003
#define IOCA2                0x0002
#define IOCA1                0x0001
#define IOCA0                0x0000

//----- WDTCON Bits --------------------------------------------------------

BIT_AT(WDTCON_ADDR,4)	WDTPS3;
BIT_AT(WDTCON_ADDR,3)	WDTPS2;
BIT_AT(WDTCON_ADDR,2)	WDTPS1;
BIT_AT(WDTCON_ADDR,1)	WDTPS0;
BIT_AT(WDTCON_ADDR,0)	SWDTEN;

//----- ADCON1 -------------------------------------------------------------

#define ADCS2                0x0006
#define ADCS1                0x0005
#define ADCS0                0x0004

//----- BANK 2 REGISTER DEFINITIONS ----------------------------------------
//----- WPUB Bits ----------------------------------------------------------

BIT_AT(WPUB_ADDR,7)	WPUB7;
BIT_AT(WPUB_ADDR,6)	WPUB6;
BIT_AT(WPUB_ADDR,5)	WPUB5;
BIT_AT(WPUB_ADDR,4)	WPUB4;

//----- IOCB --------------------------------------------------------------

#define IOCB7                0x0007
#define IOCB6                0x0006
#define IOCB5                0x0005
#define IOCB4                0x0004

//----- VRCON Bits ---------------------------------------------------------

BIT_AT(VRCON_ADDR,7)	C1VREN;
BIT_AT(VRCON_ADDR,6)	C2VREN;
BIT_AT(VRCON_ADDR,5)	VRR;
BIT_AT(VRCON_ADDR,4)	VP6EN;
BIT_AT(VRCON_ADDR,3)	VR3;
BIT_AT(VRCON_ADDR,2)	VR2;
BIT_AT(VRCON_ADDR,1)	VR1;
BIT_AT(VRCON_ADDR,0)	VR0;

//----- CM1CON0 Bits -------------------------------------------------------

BIT_AT(CM1CON0_ADDR,7)	C1ON;
BIT_AT(CM1CON0_ADDR,6)	C1OUT;
BIT_AT(CM1CON0_ADDR,5)	C1OE;
BIT_AT(CM1CON0_ADDR,4)	C1POL;

BIT_AT(CM1CON0_ADDR,2)	C1R;
BIT_AT(CM1CON0_ADDR,1)	C1CH1;
BIT_AT(CM1CON0_ADDR,0)	C1CH0;

//----- CM2CON0 Bits -------------------------------------------------------

BIT_AT(CM2CON0_ADDR,7)	C2ON;
BIT_AT(CM2CON0_ADDR,6)	C2OUT;
BIT_AT(CM2CON0_ADDR,5)	C2OE;
BIT_AT(CM2CON0_ADDR,4)	C2POL;

BIT_AT(CM2CON0_ADDR,2)	C2R;
BIT_AT(CM2CON0_ADDR,1)	C2CH1;
BIT_AT(CM2CON0_ADDR,0)	C2CH0;

//----- CM2CON1 Bits -------------------------------------------------------

BIT_AT(CM2CON1_ADDR,7)	MC1OUT;
BIT_AT(CM2CON1_ADDR,6)	MC2OUT;
BIT_AT(CM2CON1_ADDR,1)	T1GSS;
BIT_AT(CM2CON1_ADDR,0)	C2SYNC;

//----- ANSEL --------------------------------------------------------------

#define ANS7                 0x0007
#define ANS6                 0x0006
#define ANS5                 0x0005
#define ANS4                 0x0004
#define ANS3                 0x0003
#define ANS2                 0x0002
#define ANS1                 0x0001
#define ANS0                 0x0000

//----- BANK 3 REGISTER DEFINITIONS ----------------------------------------
//----- EECON1 -------------------------------------------------------------

#define EEPGD                0x0007
#define WRERR                0x0003
#define WREN                 0x0002
#define WR                   0x0001
#define RD                   0x0000

//----- PSTRCON -------------------------------------------------------------

#define STRSYNC              0x0004
#define STRD                 0x0003
#define STRC                 0x0002
#define STRB                 0x0001
#define STRA                 0x0000

//----- SRCON ---------------------------------------------------------------

#define SR1                  0x0007
#define SR0                  0x0006
#define C1SEN                0x0005
#define C2REN                0x0004
#define PULSS                0x0003
#define PULSR                0x0002

//==========================================================================
//
//       RAM Definition
//
//==========================================================================

//         __MAXRAM H'1FF'
//         __BADRAM H'08'-H'09', H'13'-H'14', H'18'-H'1B'
//         __BADRAM H'88'-H'89', H'91', H'93'-H'94', H'98'-H'9D'
//         __BADRAM H'108'-H'109', H'110'-H'114', H'117', H'11C'-H'11D'
//         __BADRAM H'188'-H'189', H'18E'-H'19C', H'19F'-H'1EF'

//==========================================================================
//
//       Configuration Bits
//
//==========================================================================

#define _FCMEN_ON            0x3FFF
#define _FCMEN_OFF           0x37FF
#define _IESO_ON             0x3FFF
#define _IESO_OFF            0x3BFF
#define _BOD_ON              0x3FFF
#define _BOD_NSLEEP          0x3EFF
#define _BOD_SBODEN          0x3DFF
#define _BOD_OFF             0x3CFF
#define _CPD_ON              0x3F7F
#define _CPD_OFF             0x3FFF
#define _CP_ON               0x3FBF
#define _CP_OFF              0x3FFF
#define _MCLRE_ON            0x3FFF
#define _MCLRE_OFF           0x3FDF
#define _PWRTE_OFF           0x3FFF
#define _PWRTE_ON            0x3FEF
#define _WDT_ON              0x3FFF
#define _WDT_OFF             0x3FF7
#define _LP_OSC              0x3FF8
#define _XT_OSC              0x3FF9
#define _HS_OSC              0x3FFA
#define _EC_OSC              0x3FFB
#define _INTRC_OSC_NOCLKOUT  0x3FFC
#define _INTRC_OSC_CLKOUT    0x3FFD
#define _EXTRC_OSC_NOCLKOUT  0x3FFE
#define _EXTRC_OSC_CLKOUT    0x3FFF
#define _INTOSCIO            0x3FFC
#define _INTOSC              0x3FFD
#define _EXTRCIO             0x3FFE
#define _EXTRC               0x3FFF

//         LIST
#endif
